version: '3.3'

networks:
    default:
        driver: bridge

services:
    node:
        container_name: node
        volumes:
            - ./inc-digital/:/var/www/html/wp-content/themes/inc-digital
        ports:
            - 3030:3000
        build:
            context: ./inc-digital
            dockerfile: Dockerfile.node
        restart: always

    phpmyadmin:
        platform: linux/amd64
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:5.1.1
        restart: always
        ports:
            - 8190:80 # Alterado para porta 8190 no host
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    db:
        container_name: db
        image: mariadb:10.5.8
        volumes:
            - ./database:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    wordpress:
        container_name: wordpress
        depends_on:
            - db
        image: wordpress:latest
        volumes:
            - ./inc-digital:/var/www/html/wp-content/themes/inc-digital
        ports:
            - 8099:80 # Alterado para porta 8099 no host
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

    wpcli:
        container_name: wpcli
        depends_on:
            - db
            - wordpress
        image: wordpress:cli
        command: tail -f /dev/null
        volumes_from:
            - wordpress
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
